Repository auth0/react-native-auth0, pull requests merged in 2019-10, with the labels that each got.

#242 Release v2.0.0
  CHANGELOG.md
  DEVELOPMENT.md
  docs/Auth.html
  docs/Auth0.html
  docs/Auth0.module.exports.html
  docs/Users.html
  docs/WebAuth.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  docs/src_auth_index.js.html
  docs/src_management_users.js.html
  docs/src_webauth_index.js.html
  package.json
  src/networking/telemetry.js
Labels: tiny

#246 Update README.md
  README.md
Labels: [Goalie] Review Required, small

#248 Specify commit sha for codecov, and exit with 1 if not successful
  .circleci/config.yml
Labels: tiny

#243 Improved OIDC compliance
  .jsdoc.json
  package.json
  src/jwt/__tests__/jwt.spec.js
  src/jwt/__tests__/pubkey.pem
  src/jwt/index.js
  src/jwt/signatureVerifier.js
  src/jwt/validator.js
  src/webauth/index.js
  yarn.lock
Labels: CH: Security, medium
