Repository auth0/react-native-auth0, pull requests merged in 2020-04, with the labels that each got.

#299 [Snyk] Security upgrade crypto-js from 3.1.9-1 to 3.3.0
  package.json
  yarn.lock
Labels: CH: Security

#300 Fixed tag in Podspec
  ios/A0Auth0.podspec
Labels: CH: Fixed, tiny

#302 Release v2.3.1
  CHANGELOG.md
  docs/Auth.html
  docs/Auth0.html
  docs/Auth0.module.exports.html
  docs/Users.html
  docs/WebAuth.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  docs/src_auth_index.js.html
  docs/src_management_users.js.html
  docs/src_webauth_index.js.html
  package.json
  src/networking/telemetry.js
Labels: small
