Repository auth0/react-native-auth0, pull requests merged in 2020-08, with the labels that each got.

#329 Fix the www-authenticate header parsing logic
  src/auth/__tests__/__snapshots__/index.spec.js.snap
  src/auth/__tests__/index.spec.js
  src/auth/authError.js
Labels: CH: Fixed, small

#330 Release v2.6.0
  CHANGELOG.md
  docs/Auth.html
  docs/Auth0.html
  docs/Auth0.module.exports.html
  docs/Users.html
  docs/WebAuth.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  docs/src_auth_index.js.html
  docs/src_management_users.js.html
  docs/src_webauth_index.js.html
  package.json
  src/networking/telemetry.js
Labels: tiny

#332 Add Bot Protection guidance to README [SDK-1898]
  README.md
Labels: CH: Added, documentation, small
