Repository auth0/react-native-auth0, pull requests merged in 2021-04, with the labels that each got.

#363 Capture and surface error when browser app is not available [SDK-2224]
  README.md
  android/src/main/java/com/auth0/react/A0Auth0Module.java
Labels: CH: Fixed, review:small

#366 Release v2.8.1
  CHANGELOG.md
  docs/Auth.html
  docs/Auth0.html
  docs/Auth0.module.exports.html
  docs/Users.html
  docs/WebAuth.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  docs/src_auth_index.js.html
  docs/src_management_users.js.html
  docs/src_webauth_index.js.html
  package.json
  src/networking/telemetry.js
Labels: review:tiny

#369 Fix for Xcode 12.5 [SDK-2545]
  ios/A0Auth0.m
Labels: CH: Fixed, review:tiny

#370 Add ephemeral session information to the README
  README.md
Labels: documentation, review:tiny

#372 Release v2.8.2
  CHANGELOG.md
  docs/Auth.html
  docs/Auth0.html
  docs/Auth0.module.exports.html
  docs/Users.html
  docs/WebAuth.html
  docs/global.html
  docs/index.html
  docs/index.js.html
  docs/src_auth_index.js.html
  docs/src_management_users.js.html
  docs/src_webauth_index.js.html
  package.json
  src/networking/telemetry.js
Labels: review:small
